[build]
  command = "pip install -r requirements.txt"
  functions = "netlify/functions"
  publish = "public"

[build.environment]
  PYTHON_VERSION = "3.11"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"

[dev]
  command = "uvicorn app.main:app --reload --port 8000"
  targetPort = 8000
  port = 8888
