[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"

# API redirects for Netlify Functions
[[redirects]]
  from = "/api/v1/auth/register"
  to = "/.netlify/functions/auth-register"
  status = 200

[[redirects]]
  from = "/api/v1/auth/login"
  to = "/.netlify/functions/auth-login"
  status = 200

[[redirects]]
  from = "/api/v1/rentals/vehicles"
  to = "/.netlify/functions/vehicles-list"
  status = 200

[[redirects]]
  from = "/api/v1/rentals"
  to = "/.netlify/functions/rentals-create"
  status = 200

[[redirects]]
  from = "/api/v1/maintenance/services"
  to = "/.netlify/functions/maintenance-services"
  status = 200

[[redirects]]
  from = "/api/v1/store/products"
  to = "/.netlify/functions/store-products"
  status = 200

# SPA fallback (must be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
